services:
  - type: web
    name: civic-authority-api
    runtime: node
    region: singapore
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        value: https://the-civic-authority-theta.vercel.app
